version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
  api:
    build:
      context: ./simple-bank-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: api
    depends_on:
      - postgres
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
      - ./simple-bank-api:/app # Look at the server directory and copy everything into the app folder in the container
  web-app:
    container_name: web-app
    build:
      context: ./simple-bank-web
      dockerfile: Dockerfile
    restart: unless-stopped
    stdin_open: true
    volumes:
      - "/app/node_modules"
      - "./simple-bank-web:/app"
    ports:
      - 3001:3000
